---
date: "2020-10-06"
slug: take-it-easy
title: 幸得诸君慰平生
categories:
  - 推荐文章
tags:
  - 人文社会
  - 杂谈随笔
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    self_contained: true
description: "《幸得诸君慰平生》故园风雨前 著。人这一辈子要经历很多人和事，伴随一些思考，人和事构成了人生，当你老了，走不动了，炉火旁取暖，愿诸君都还有青春可以回忆！"
---

```{css}
#| echo: false

iframe {
  text-align: center;
  display: block;
  margin: auto;
  width: 90%;
}
```


> 世界上只有一种英雄主义，就是看清生活的真相之后依然热爱它。
>
> --- 罗曼·罗兰

1.   今天在地铁上看到一个很漂亮的妹子的包上有这样一句话：Little by little, one travels far。我想了一会儿，有个很得意的翻译 --- 「一点一点去旅行」--- 是按字面意思来的，其实，我猜这可能是个谚语，文邹邹的表达可能是不积跬步无以至千里，但是没有意境。其实，我当时还想到一句广告词，那就是让心灵去旅行，而要做到这一点，一定是一点一点地渐变过程，要享受这个过程，心灵慢慢就变了！那句童叟皆知的谚语只是在强调结果，绝没有一点一点这样来得具象，并强调过程！

1.  [《一往无前》](https://www.bilibili.com/video/av371631403/) 是雷军在小米十周年上的公开演讲，他用一个半小时讲述了十年创业历程。不忘初心 ——「做全球最好的手机，只卖一半的价钱，让每个人都能买得起」。互联网（谷歌）+ 软件（微软）+硬件（摩托罗拉）三位一体，创立小米，对纯硬件公司降维打击。

    他总结，创业过程中，人永远是第一位的，找合适的人太难了，难在没有花足够的时间和耐心，找人不是「三顾茅庐」，而是要「三十次顾茅庐」。坚持做对的事情，用奥卡姆剃刀留下最核心的东西，并将其做到极致，能解决用户痛点的就是最核心的东西。用互联网的方法论做手机：专注、极致、口碑和快，小步快跑，靠用户口碑传播。用真诚搞定国际顶级供应链，找投资人拿钱，拿到入场的门票。发布红米手机，带动国内产业链。获取用户反馈，学习优秀企业、交流经验。没有任何一个成功是不冒风险的，直面风险，豁出去干！作为 CEO，时间和精力的分配要跟随阶段变化做相应调整。打造极致性价比带来便宜无好货的原罪，企业越来越大，高速发展掩盖了亏空，形势严峻，开始质量运动，质量是公司的生命线。创新决定我们飞得有多高，质量决定我们飞得有多远。稳住阵脚比出奇招创新更重要。用营销策略定价，用品质搞定用户。深刻反思总结，五年后手机怎么做，培养战略眼光。工程师是最重要的资产，可以直面 CEO，打造工程师文化，塑造小米公司的能力模型。好的想法，立刻开始干，不要考虑预算，不要考虑时间表，不要考虑量产性，做完为止，给予工程师最大的参与感，去实现抱负。小米商业模式在全球复制，成功往往不是规划出来的，危机是你想不到的机会。客户至上，做好继任，从普通商业公司成为百年老店，优秀的公司赚取利润，伟大的公司赢得人心。小米10年是移动互联网10年，小米传记《一往无前》出版，用公司文化吸引更多优秀的人。


1.  一堂培训课上，主讲人给每个人都发了一张纸，纸上画了两个轴，横轴代表年岁，7 年为一阶段，纵轴代表心理感受，越往上表示越开心、幸福、快乐，越往下表示越消极、痛苦，悲伤，以及代表这些心理感受的笑脸和苦脸贴纸。每个人把自己的人生地图画完后，展示给其他人看，并交流对未来的憧憬。我的人生地图如下：

    
    ```{r}
    #| label: life
    #| echo: false
    #| dev: "ragg_png"
    #| fig.width: 7
    #| fig.height: 4
    #| fig.cap: "我的人生地图"
    
    life <- data.frame(
      x = c(
        10, 13, 16, 19,
        26, 27, 29, 32,
        37
      ),
      y = c(
        10, -3, 6, -5,
        -10, 7, 6, 9,
        6.5
      ),
      z = c(
        "smile", "sob", "smile", "sob",
        "sob", "smile", "smile", "smile",
        "smile"
      )
    )
    
    life <- within(life, {
      z <- emojifont::emoji(z)
    })

    library(ggplot2)
    library(emojifont)

    ggplot(data = life, aes(x = x, y = y, color = z)) +
      geom_point(size = 10, alpha = 0.2, show.legend = FALSE) +
      scale_x_continuous(
        breaks = 7 * 0:7,
        labels = paste(7 * 0:7, "岁"),
        limits = c(0, 49),
        minor_breaks = NULL
      ) +
      scale_y_continuous(breaks = NULL, limits = c(-13, 13)) +
      geom_hline(yintercept = 0, color = "gray") +
      geom_text(aes(label = z),
        family = "EmojiOne",
        size = 20, vjust = 0.12, show.legend = FALSE
      ) +
      scale_color_manual(values = c("#34A853", "#FBBC05")) +
      theme_minimal() +
      theme(
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 20),
        axis.title.y = element_text(size = 25)
      ) +
      labs(x = "", y = "心理感受")
    ```

    -   0-7 岁没什么感觉，可能太小了，记忆有点模糊。
    -   8-14 岁是快乐的童年、少年生活，和朋友、同学到处疯玩，上山爬树，下山摸鱼，弄脏了爸妈给新买的衣服，被脱光了扔到外面。
    -   15-21 岁是忙碌的中考、高考和大学生活，越来越少和朋友、同学去玩，悲喜随着分数起起伏伏。
    -   22-28 岁是散养自学以及从学校进入社会的闯荡生活，临近毕业被狠狠地教育了一回怎么做人，感谢学校帮我打开了带宽，让我不至于被一块小石头绊倒。
    -   29-35 岁是逐步走向成熟的的阶段，慢慢找到自己的生活和工作原则，以微笑面对起起伏伏的性情，不再大喜大悲。
    -   36-42 岁不知道会是什么样，但是我给它一个笑脸。
    -   43-49 岁完全不知道自己会是什么样，会以什么样的心态过什么样的生活，留白。


1.  洛洛，一个自童年起就坐在轮椅上的姑娘，对生活依然笑脸相迎的姐姐。我是在南锣鼓巷里遇见她的，她正在那卖自己写的书，我在她旁边的不远处吃着没有臭味的长沙臭豆腐，一边吃一边看着她那边偶尔驻足的行人。今天是周日，来往的人很多，我看了好一会儿，买的人很少。直到我把这臭豆腐吃完，擦了嘴，送了垃圾，才走了过去，她笑着说随便看。她面前放着两摞书，人物封面上充满活力的微笑吸引了我，我随手拿起了左手边的《心的翅膀》，我此时在想她是遭遇了什么不幸才坐上轮椅的，又是怎样在轮椅上写完三本书的。我快速地看了前勒口上的一点简介：

    > 没有上过学，喜欢文字。  
    爱旅行，爱幻想，爱臭美，爱写字，爱阅读，  
    爱电影，爱音乐。  
    轻度表达障碍症。  
    喜欢做女红，给娃娃做衣服，编中国结。  
    喜欢格子，各种格子物件。  
    彩虹控，喜欢彩虹和所有彩虹色的东西。  
    喜欢本子。  
    开过饭店，摆过地摊。  
    未来想开一间咖啡店，  
    读万卷书，行万里路。  
    在离开世界之前走遍世界。  
    无论曾经历多少坎坷与磨难，仍然坚信世间美好。  
    坚信那个单纯微笑乐观的那个小小的我，  
    无论在这个世界的任何角落，都会认真生活。

    接着看了一段自序，在文学书里，文笔可能一般，然后，又看了看书籍出版年月，是2005年出的，距今17年了，岁月在她脸上留下了痕迹。可不是，我那时还在读小学呢。我曾近距离接触过写书的过程，知道写书不容易，写好就更难了，对她更是难上加难了，所以三分出于同理心，七分出于她的微笑乐观，我买了她自传，也就是这本《心的翅膀》。对生活始终充满乐观的态度是值得很多人学习的，而这样的人就在我们身边，而不是遥不可及的霍金。

1.  「书中自有颜如玉，书中自有黄金屋」，其实除了劝学以外，我觉得还有另一层意思，就是书比黄金屋和颜如玉还要难得，现代人可能不好理解，钱穆先生的《中国历代政治得失》讲得好，历史上，能够占有书籍的人都家财万贯，因为书比黄金屋和颜如玉更加稀缺。掌握了书籍这种稀缺资源，就可以读私塾，念四书五经等经世致用的道德文章，进而走向仕途，光宗耀祖。财富、权力间接通过书籍一代代传承累积。这是自汉代以来逐渐形成的朝廷制度，从汉之察举到唐之科举，而后延续至清末，历朝历代的社会阶层几乎以士、农、工、商为序。

1.  1901年钦差大臣奕匡、两江总督李鸿章代表晚清政府签订辛丑条约，电视剧《走向共和》第 26 集有一段台词描述的满是无奈：

    > 人最难写的就是自己的名字，签在这卖国条约上，就是千古骂名，王爷还年轻，路还长着呢，还是由我来吧。

    时人总说李鸿章是走狗和卖国贼，签订了丧权辱国的条约，签订条约只是一个结果，丧权辱国是因为清廷闭关锁国几十年，特别是乾隆晚年种下的因。乾隆皇帝用几代人积攒的血汗成就自己十大武功，一心直追圣祖康熙，晚年好大喜功，所谓「天朝」自此而来，嘉庆帝无雍正帝的魄力和手段，不敢改闭关锁国的祖制，未能扭转吏治腐败的局面。

1.  《道德文章垂范人间：纪念许宝騄先生百年诞辰》，许先生的祖父许祐身官拜清朝苏州府知府，相当于现今发达城市的市委书记兼市长。许先生的父亲许引之官拜清朝两浙盐运使，清朝盐、铁、茶都是官营，一些电视剧里形容是大清最肥的缺，级别比知府还高。因此，可以说是书香门第、家境殷实，许先生也从小接受了良好的私塾教育，幼时成名。许先生成于父祖家荫，晚年亦毁于此。

    历史的车轮无论是向前滚还是向后退，个人都是渺小的，无论你多有才华。纵观许先生一生，结合历史发展和时代背景，可以说是云谲波诡、世事难料，不免感慨人之渺小。1901 年，庚子赔款，中国彻底沦为半殖民地半封建社会。1910年，许先生出生。1911年，辛亥革命开始。1912年，清宣统帝退位，中华民国建立。1938 许先生毕业于英国伦敦大学学院，师从 E. S. Pearson 埃贡·皮尔逊 和 Jerzy Neyman 乔治·耐曼。

    政治宣传和个人信仰之间实际上存在巨大的鸿沟。1949年建国后，短短十余年后，便经历了十余年的政治运动，特别是1967-1976年间的无产阶级文化大革命，恐怕不少知识分子的信仰是坍塌的，想想建国前我党对知识分子的抢救会觉得特别讽刺。这些知识分子相信了共产党的宣传，对共产党的统治抱有希望和幻想。建国以来，领导人在如何走社会主义道路上的探索，包括大跃进、人民公社等都极富理想主义色彩，是幼稚的一面。马克思、恩格斯的社会主义革命理论传入中国，而理论和实践之间的差距比想象的要大很多，从城市攻坚到农村包围城市，到摸着石头过河，社会理论用于实践往往又比科学理论用于实践带来的危害大得多。

    无论是看个人简介、看书、看文章、看访谈都能看到一些自己没有经历过的、甚至也经历不了的故事和人生，从中体会到些许感悟和触动。统计学的发展可能落后于美国至少60年，大家看到的那些名家只是幸存者偏差里浮现出来的离群点。


1.  最近发现，浪姐已经出到第三季了，还没来得及看，第一季里吴昕走之前有段话很精彩，她是那个被网络贴满标签的「小短腿」，「透明人」，这段话让人感觉与这些标签完全挨不着边。

    > 没有什么遗憾，然后我想开开心心地走，想把很多的东西留在心里，然后我想把我的乐观成长和坚强留在这。你要永远相信你的承受能力和认知范围是超乎你想象的，不管走到哪一步，勇敢地克服自己性格上的弱点，勇敢地去突破自己心理上的接受度，你会收获更多。
    >
    > --- 《乘风破浪》吴昕

1.  最后，一首[黄沾](https://en.wikipedia.org/wiki/James_Wong_Jim)作词郑少秋演唱的「笑看风云」送给自己。

    <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="https://music.163.com/outchain/player?type=2&id=1477530893&auto=1&height=66"></iframe>

    > 谁没有一些 刻骨铭心事  
      谁能预计后果  
      谁没有一些 旧恨心魔  
      一点点无心错  
      谁没有一些 得不到的梦  
      谁人负你负我多  
      谁愿意解释 为了什么  
      一笑已经风云过  
      活得开心 心不记恨  
      为今天欢笑唱首歌  
      任胸间吸收新的快乐  
      在晚风中敞开心锁  
      谁愿记沧桑 匆匆往事  
      谁人是对是错  
      从没有解释 为了什么  
      一笑看风云过
