---
title: 一些 MacOS 上的软件
author: 黄湘云
date: '2020-03-21'
slug: softwares-for-macos
output:
  blogdown::html_page:
    toc: true
link-citations: true
categories:
  - 统计软件
tags:
  - 技术笔记
description: "软件环境配置是个既麻烦又耗时的苦力活，笔者曾经在 Windows 上折腾多年，换过几次电脑，工作之后，转向 MacOS 系统，又开始折腾，人生苦短，现收集整理出来，以后遇到新的坑也会填上来，尽量节省一些不必要的重复折腾。一些历史的折腾也搬上来了，生命不息，重装不止！"
---


# 设置 MacOS

-   [Mac 截图去阴影等常用设置](https://macos-defaults.com/)

-   [自定义终端的命令行提示符](https://stackoverflow.com/questions/37286971/)

-   解决 [raw.githubusercontent.com port 443: Connection refused](https://blog.csdn.net/Rainbow1995/article/details/111475551)
    在网站 <https://ipaddress.com/> 输入 `raw.githubusercontent.com` 拿到 IP 地址，添加到 hosts 文件。
    
    ```bash
    sudo vi /etc/hosts
    ```
    ```
    185.199.108.133   raw.githubusercontent.com
    185.199.109.133   raw.githubusercontent.com
    185.199.110.133   raw.githubusercontent.com
    185.199.111.133   raw.githubusercontent.com
    ```

-   配置 MacOS 终端：MacOS 自带 [zsh](https://github.com/zsh-users/zsh)，只需安装 [Oh My Zsh](https://github.com/ohmyzsh/ohmyzsh) 配置工具、[nerd-font](https://github.com/ryanoasis/nerd-fonts) 图标字体和 [powerlevel10k](https://github.com/romkatv/powerlevel10k) 主题。

    ```bash
    # 安装 fira-code 字体及其配套的图标字体
    brew install --cask font-fira-code font-fira-code-nerd-font
    ```


# 配置终端

[pure](https://github.com/sindresorhus/pure) 是一个极简风格的终端配置工具

```bash
brew install pure
```

在 `~/.zshrc` 添加

```
# .zshrc
autoload -U promptinit; promptinit
prompt pure
```

安装插件 [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting/) 语法高亮

```bash
brew install zsh-syntax-highlighting
```

安装插件 [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) 自动建议

```
brew install zsh-autosuggestions
```

安装插件 [zsh-completions](https://github.com/zsh-users/zsh-completions) 补全

```bash
brew install zsh-completions
```

安装插件 [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete) 自动补全

```bash
brew install zsh-autocomplete
```



# 配置 Git

```bash
git config --global user.name "Xiangyun Huang"
git config --global user.email "xiangyunfaith@outlook.com"
```

# 常用软件

```bash
brew install --cask font-noto-sans-cjk-sc font-noto-serif-cjk-sc
brew install --cask font-noto-sans font-noto-serif
brew install imagemagick proj gdal geos udunits libomp pkg-config
```



# 其它软件


## 办公软件


```bash
brew install --cask notion jasp
brew install --cask adobe-creative-cloud
```

视频编辑器 [openshot-video-editor](https://github.com/OpenShot/openshot-qt) (<https://www.openshot.org/zh-hans/>)

```bash
brew install --cask openshot-video-editor
```

刘志进实验室有很多免费音乐，支持外链，可以插入博客 <https://music.liuzhijin.cn/>

[shotcut](https://github.com/mltframework/shotcut)

```bash
brew install --cask shotcut
```

[blender](https://github.com/blender/blender) (<https://www.blender.org/>)

```bash
# 3D 建模
brew install --cask blender

# Github CLI 命令行工具
brew install tig gh
brew install tree gnupg

# LaTeX 代码块样式
# https://www.ctan.org/pkg/codebox
```

[plantuml](https://plantuml.com/) 提供 UML 统一建模语言 

```bash
brew install plantuml
```

[asymptote](https://asymptote.sourceforge.io/) 提供一种矢量图形编程语言，像 TikZ 支持 LaTeX，[asymptote 宏包](https://ctan.org/pkg/asymptote)及其[使用文档](https://asymptote.sourceforge.io/asymptote.pdf)。

```bash
brew install asymptote
```

数据科学平台

```bash
brew install --cask rapidminer-studio data-science-studio
```

[Orange](https://github.com/biolab/orange3) (<https://orangedatamining.com/>) 是开源的数据挖掘软件， 每一个操作都是一个组件，将组件连接起来就是工作流，可视化数据编程

```bash
# 数据挖掘软件
brew install --cask orange
# 收费的商业智能工具
brew install --cask tableau 
```

# 绘图软件 

## Gifski

安装 [Rust 软件](https://www.rust-lang.org/) 以及 [Gifski](https://gif.ski/) 转化器，它可将视频、图片文件转化为 GIF 动图，且转化效率和质量非常高。 

1.  安装 Rust 库 gifski 

    ```bash
    # 安装 rust
    brew install rust
    # 安装 gifski 库
    cargo install gifski
    ```

    在 `~/.cargo/config` 里配置就近的镜像地址加快[cargo](https://github.com/nabijaczleweli/cargo-update)下载速度，下面配置的是上海交通大学 Linux 用户组 (SJTUG)  维护的[镜像站点](https://mirrors.sjtug.sjtu.edu.cn/)。
    
    ```
    [source.crates-io]
    replace-with = "sjtu"
    
    [source.sjtu]
    registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index"
    ```
    
    将路径 `~/.cargo/bin` 添加到 PATH 变量里，接着就可以直接使用 gifski 命令行工具了，它有几个参数，如下：
    
    ```bash
    gifski --help
    ```


    帮助文档非常简单，就不翻译了，举个例子，下面将一段视频 `INPUT.mov` 转化为 GIF 动图 `OUTPUT.gif`。
    
    ```bash
    gifski -W 800 -H 600 INPUT.mov -o OUTPUT.gif
    ```

1.  安装 gifski 软件

    ```bash
    brew install gifski
    ```


## gnuplot

[gnuplot](http://www.gnuplot.info/) 是开源的绘图软件，不像 gimp，它是命令行驱动。

```bash
brew install gnuplot
```

将下面的命令放入文件 `~/.gnuplot` 自定义字体

```
set term qt font "Noto Sans"
```

查看本机安装的字体

```bash
fc-list : family | sort
```


# 用 miniconda 配置 Python 虚拟环境

`~/.condarc` 指定虚拟环境所在目录

``` yaml
envs_dirs:
  - /opt/miniconda-virtualenvs/
```

详见 miniconda [官方文档](https://docs.conda.io/en/latest/miniconda.html)

``` bash
# 安装 miniconda
brew install --cask miniconda
# 初始化，将配置写入当前 Shell 环境，比如 .zshrc
conda init "$(basename "${SHELL}")"   

# 创建环境
conda create -n r-reticulate python=3.8
# 激活环境
conda activate r-reticulate
# 安装模块
conda install --yes --file requirements.txt

# 更新升级 conda
conda update -n base -c defaults conda

# 退出虚拟环境
conda deactivate
```

``` bash
# 指定安装路径和 Python 版本
conda create -p /opt/miniconda-virtualenvs/r-reticulate python=3.7
# 移除虚拟环境
conda env remove -p /opt/miniconda-virtualenvs/r-reticulate
# 更新 miniconda
conda update conda
```



# 用 Gollum 搭建知识管理系统

用 [Gollum](https://github.com/gollum/gollum) 创建 wiki 随时记下个人笔记，gollum 源自电影《指环王》里的角色咕噜。系统环境如下

``` bash
gem env
```

    RubyGems Environment:
      - RUBYGEMS VERSION: 3.0.3
      - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin20]
      - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.6.0
      - USER INSTALLATION DIRECTORY: /Users/你的账户名/.gem/ruby/2.6.0
      - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
      - GIT EXECUTABLE: /usr/bin/git
      - EXECUTABLE DIRECTORY: /usr/local/bin
      - SPEC CACHE DIRECTORY: /Users/你的账户名/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
      - RUBYGEMS PLATFORMS:
        - ruby
        - universal-darwin-20
      - GEM PATHS:
         - /Library/Ruby/Gems/2.6.0
         - /Users/你的账户名/.gem/ruby/2.6.0
         - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
         - :sources => ["https://mirrors.tuna.tsinghua.edu.cn/rubygems/"]
         - :concurrent_downloads => 8
      - REMOTE SOURCES:
         - https://mirrors.tuna.tsinghua.edu.cn/rubygems/
      - SHELL PATH:
         - /Users/你的账户名/.gem/ruby/2.6.0/bin

将 `/Users/你的账户名/.local/share/gem/ruby/2.6.0/bin` 添加到 PATH 变量里，修改修改镜像源，加快下载速度

``` bash
gem sources --add https://mirrors.tuna.tsinghua.edu.cn/rubygems/ --remove https://rubygems.org/
```

安装好 Xcode 库后，安装一些编译环境，比如 cmake，一些 [gollum](https://github.com/gollum/gollum) 依赖的库需要编译安装，这些库是用 cmake 创建的项目。更新自带的库

``` bash
sudo gem update
```

然后安装 gollum

``` bash
brew install cmake pkg-config
gem install --user-install gollum
```

注意 :warning: 由于权限问题，不能安装到系统目录，实际上，也建议安装到非系统目录，即当前账户下的目录，截止 2021-03-06 安装的最新稳定版本 gollum 5.2.1。创建一个目录，并用 git 初始化， gollum 是用 git 来做版本管理的，所以要先初始化，然后使用 gollum 服务，启动 wiki

``` bash
gollum /path/to/wiki
```

最后，预览 Wiki 网页，打开 <http://localhost:4567>，gollum 默认使用 4567 端口号，如果分支使用 main， 那么启动的时候要加参数 `--ref` 指定为 main

``` bash
gollum --ref main --emoji --allow-uploads=dir /path/to/wiki
```

> 注意：先想好目录结构，不然会很乱，以后改起来就麻烦了！

