---
title: 《地区分布图及其应用》番外篇
author: 黄湘云
date: '2022-06-02'
slug: choropleth-map-gossip
categories:
  - 统计应用
tags:
  - 数据操作
  - 专题地图
  - 项目回顾
  - 区域数据
  - Base R
  - tidyverse
  - ggplot2
output:
  blogdown::html_page:
    toc: true
link-citations: true
bibliography: 
  - refer.bib
description: "有的文章关注单个小功能、小模块地逐一介绍，非常类似某些 R 包的帮助文档，而有的需要企业级探索和实践，这就需要踩坑填坑，多方对比，总结经验，摸索出一条好实现、好维护、好效果的路。"
---


<div id="TOC">
<ul>
<li><a href="#写作背景" id="toc-写作背景">写作背景</a></li>
<li><a href="#何谓专题地图" id="toc-何谓专题地图">何谓专题地图</a></li>
<li><a href="#又一绘图方案" id="toc-又一绘图方案">又一绘图方案</a>
<ul>
<li><a href="#数据准备" id="toc-数据准备">数据准备</a>
<ul>
<li><a href="#观测数据" id="toc-观测数据">观测数据</a></li>
<li><a href="#地图数据" id="toc-地图数据">地图数据</a></li>
<li><a href="#数据合并" id="toc-数据合并">数据合并</a></li>
</ul></li>
<li><a href="#数据展示" id="toc-数据展示">数据展示</a></li>
<li><a href="#经验总结" id="toc-经验总结">经验总结</a></li>
</ul></li>
<li><a href="#数据操作杂谈" id="toc-数据操作杂谈">数据操作杂谈</a>
<ul>
<li><a href="#长宽格式要怎么转" id="toc-长宽格式要怎么转">长宽格式要怎么转</a></li>
<li><a href="#base-r-永远是-base-r" id="toc-base-r-永远是-base-r">Base R 永远是 Base R</a></li>
<li><a href="#此-filter-非彼-filter" id="toc-此-filter-非彼-filter">此 filter 非彼 filter</a></li>
<li><a href="#经验总结-1" id="toc-经验总结-1">经验总结</a></li>
</ul></li>
<li><a href="#也谈写作历程" id="toc-也谈写作历程">也谈写作历程</a>
<ul>
<li><a href="#预期目标" id="toc-预期目标">预期目标</a></li>
<li><a href="#内容设想" id="toc-内容设想">内容设想</a></li>
<li><a href="#读者反馈" id="toc-读者反馈">读者反馈</a></li>
<li><a href="#评审反馈" id="toc-评审反馈">评审反馈</a></li>
</ul></li>
<li><a href="#环境信息" id="toc-环境信息">环境信息</a></li>
<li><a href="#参考文献" id="toc-参考文献">参考文献</a></li>
</ul>
</div>

<style type="text/css">
.sidebar {
  border: 1px solid #ccc;
  border-left-width: 5px;
  border-radius: 5px;
  padding: 1em;
  margin: 1em 0;
}

.full-width {
  width: 100vw;
  margin-left: calc(50% - 50vw);
}

.full-width .caption {
  text-align: center;
}

figure {
  text-align: center;
}

div.img {
  text-align: center;
  display: block; 
  margin-left: auto; 
  margin-right: auto;
}

blockquote > p:last-child {
  text-align: right;
}
blockquote > p:first-child {
  text-align: inherit;
}
</style>
<div id="写作背景" class="section level1">
<h1>写作背景</h1>
<p>有的文章关注单个小功能、小模块地逐一介绍，非常类似某些 R 包的帮助文档，而有的需要企业级探索和实践，这就需要踩坑填坑，多方对比，总结经验，摸索出一条好实现、好维护、好效果的路。<a href="/2022/04/choropleth-map/">《地区分布图及其应用》</a>就属于后者，它的定位是面向入门到进阶的读者。在开头没有交代清楚目标读者，而笔者<strong>想当然</strong>地认为读者一看内容便知定位。</p>
<p>下面分四个部分写《地区分布图及其应用》的番外篇：</p>
<ol style="list-style-type: decimal">
<li><strong>何谓专题地图</strong>：面向初次接触空间区域数据可视化的读者，阐明原文覆盖的内容。</li>
<li><strong>又一</strong>绘图方案：以<strong>极其详细</strong>的方式介绍 <strong>ggplot2</strong> + <strong>maps</strong> 绘图方法，其前置的数据探查、数据处理的过程也值得借鉴，这些都是原文没有展开的内容。</li>
<li><strong>数据操作杂谈</strong>：个人经验之谈甚多，内容是有偏的。</li>
<li><strong>部分</strong>写作历程：对原文写作过程的回顾，一些背后的所思所想。</li>
</ol>
</div>
<div id="何谓专题地图" class="section level1">
<h1>何谓专题地图</h1>
<p>目前，R 语言社区可以用来绘制地区分布图（Choropleth map）的 R 包有 <strong>maps</strong> 包<span class="citation">(<a href="#ref-maps" role="doc-biblioref">Becker et al. 2021</a>)</span>，<strong>sf</strong> 包<span class="citation">(<a href="#ref-Pebesma2018" role="doc-biblioref">Pebesma 2018</a>)</span>，<strong>tmap</strong> 包<span class="citation">(<a href="#ref-Tennekes2018" role="doc-biblioref">Tennekes 2018</a>)</span>和 <strong>mapsf</strong> 包<span class="citation">(<a href="#ref-mapsf" role="doc-biblioref">Giraud 2022</a>)</span>等等。<strong>tmap</strong> 包的标题为 Thematic Maps（专题地图），
<strong>mapsf</strong> 包的标题为 Thematic Cartography（专题制图），
<strong>maps</strong> 包的标题为 Draw Geographical Maps（绘制地理地图），从这些标题不难看出，它们不止可以绘制地区分布图，还可以绘制其它常见的地理统计图形，每个 R 包的帮助文档都有详尽的介绍，如比例符号气泡图（Proportional symbol map）、核密度地图（Kernel density map）和变形地图（Cartogram）等等。统计之都主站发布的文章<a href="https://cosx.org/2022/05/choropleth-map/">《地区分布图及其应用》</a>在末尾还介绍了多种地区分布图的变体，它们都可以叫专题地图（Thematic Maps），可想而知，何其繁多。除了专题统计地图，还有遥感卫星地图、电子导航地图、海拔地形地图等。</p>
<div class="figure"><span style="display:block;" id="fig:cumtb-satellite"></span>
<img src="img/cumtb-satellite.png" style="width:75.0%" alt="" />
<p class="caption">图 1: 中国矿业大学（北京）学院路校区附近的卫星地图</p>
</div>
</div>
<div id="又一绘图方案" class="section level1">
<h1>又一绘图方案</h1>
<p>在文章<a href="https://cosx.org/2022/05/choropleth-map/">《地区分布图及其应用》</a>的小结部分，留了一些尾巴，其中还有<strong>两种</strong>原文提及但未给出具体代码实现和详细介绍的绘图方案，本节介绍其中一种，即用 <strong>ggplot2</strong> 包和 <strong>maps</strong> 包绘制地区分布图。仍然以 <strong>latticeExtra</strong> 包<span class="citation">(<a href="#ref-latticeExtra" role="doc-biblioref">Sarkar and Andrews 2019</a>)</span>内置的美国各郡年平均癌症死亡率数据集 USCancerRates 为例，详细介绍制作整个地区分布图的过程。</p>
<div id="数据准备" class="section level2">
<h2>数据准备</h2>
<div id="观测数据" class="section level3">
<h3>观测数据</h3>
<p>首先加载癌症死亡率数据集 USCancerRates 到 R 运行环境中。</p>
<pre class="r"><code>data(USCancerRates, package = &quot;latticeExtra&quot;)</code></pre>
<p>接下来查看数据集的基本信息。</p>
<pre class="r"><code>str(USCancerRates)</code></pre>
<pre><code>## &#39;data.frame&#39;:    3041 obs. of  8 variables:
##  $ rate.male   : num  364 346 341 336 330 ...
##  $ LCL95.male  : num  311 274 304 289 293 ...
##  $ UCL95.male  : num  423 431 381 389 371 ...
##  $ rate.female : num  151 140 182 185 172 ...
##  $ LCL95.female: num  124 103 161 157 151 ...
##  $ UCL95.female: num  184 190 206 218 195 ...
##  $ state       : Factor w/ 49 levels &quot;Alabama&quot;,&quot;Alaska&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ county      : &#39;AsIs&#39; chr  &quot;Pickens County&quot; &quot;Bullock County&quot; &quot;Russell County&quot; &quot;Barbour County&quot; ...</code></pre>
<pre class="r"><code>head(USCancerRates)</code></pre>
<pre><code>##                 rate.male LCL95.male UCL95.male rate.female LCL95.female
## alabama,pickens     363.7      311.1      423.2       151.0        123.6
## alabama,bullock     345.7      274.2      431.4       140.5        102.8
## alabama,russell     340.7      304.5      380.9       182.3        161.3
## alabama,barbour     335.9      288.9      389.1       185.3        157.2
## alabama,dallas      330.1      293.4      370.6       172.0        151.4
## alabama,greene      328.1      255.9      416.6       124.1         88.5
##                 UCL95.female   state         county
## alabama,pickens        183.6 Alabama Pickens County
## alabama,bullock        189.7 Alabama Bullock County
## alabama,russell        205.5 Alabama Russell County
## alabama,barbour        217.5 Alabama Barbour County
## alabama,dallas         195.0 Alabama  Dallas County
## alabama,greene         171.7 Alabama  Greene County</code></pre>
<p>这是一个 3041 行 8 列的数据框，每一行代表一个郡的癌症死亡率情况，各列分别是 rate.male （男性死亡率）、LCL95.male （男性死亡率的下限）、UCL95.male（男性死亡率的上限）、rate.female （女性死亡率）、LCL95.female（女性死亡率下限）、 UCL95.female（女性死亡率上限）
state（州名）和 county（郡名），一共 8 个字段。</p>
<p>为方便用 <strong>ggplot2</strong> 包分面绘图，将数据集 USCancerRates 从「宽格式」转「长格式」，R 语言内置的 <code>reshape()</code> 函数是专门用来做数据重塑操作的。</p>
<pre class="r"><code>us_cancer_rates &lt;- reshape(
  data = USCancerRates,
  varying = c(
    &quot;LCL95.male&quot;, &quot;rate.male&quot;, &quot;UCL95.male&quot;,
    &quot;LCL95.female&quot;, &quot;rate.female&quot;, &quot;UCL95.female&quot;
  ),
  times = c(&quot;男性&quot;, &quot;女性&quot;),
  v.names = c(&quot;LCL95&quot;, &quot;rate&quot;, &quot;UCL95&quot;), 
  timevar = &quot;sex&quot;, 
  idvar = c(&quot;state&quot;, &quot;county&quot;), 
  new.row.names = 1:(2 * 3041),
  direction = &quot;long&quot;
)</code></pre>
<p>重塑之后，再来看看数据集的样子，行数正好符合预期的增加一倍。</p>
<pre class="r"><code>str(us_cancer_rates)</code></pre>
<pre><code>## &#39;data.frame&#39;:    6082 obs. of  6 variables:
##  $ state : Factor w/ 49 levels &quot;Alabama&quot;,&quot;Alaska&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ county: &#39;AsIs&#39; chr  &quot;Pickens County&quot; &quot;Bullock County&quot; &quot;Russell County&quot; &quot;Barbour County&quot; ...
##  $ sex   : chr  &quot;男性&quot; &quot;男性&quot; &quot;男性&quot; &quot;男性&quot; ...
##  $ LCL95 : num  311 274 304 289 293 ...
##  $ rate  : num  364 346 341 336 330 ...
##  $ UCL95 : num  423 431 381 389 371 ...
##  - attr(*, &quot;reshapeLong&quot;)=List of 4
##   ..$ varying:List of 3
##   .. ..$ LCL95: chr [1:2] &quot;LCL95.male&quot; &quot;LCL95.female&quot;
##   .. ..$ rate : chr [1:2] &quot;rate.male&quot; &quot;rate.female&quot;
##   .. ..$ UCL95: chr [1:2] &quot;UCL95.male&quot; &quot;UCL95.female&quot;
##   .. ..- attr(*, &quot;v.names&quot;)= chr [1:3] &quot;LCL95&quot; &quot;rate&quot; &quot;UCL95&quot;
##   .. ..- attr(*, &quot;times&quot;)= chr [1:2] &quot;男性&quot; &quot;女性&quot;
##   ..$ v.names: chr [1:3] &quot;LCL95&quot; &quot;rate&quot; &quot;UCL95&quot;
##   ..$ idvar  : chr [1:2] &quot;state&quot; &quot;county&quot;
##   ..$ timevar: chr &quot;sex&quot;</code></pre>
<pre class="r"><code>head(us_cancer_rates)</code></pre>
<pre><code>##     state         county  sex LCL95  rate UCL95
## 1 Alabama Pickens County 男性 311.1 363.7 423.2
## 2 Alabama Bullock County 男性 274.2 345.7 431.4
## 3 Alabama Russell County 男性 304.5 340.7 380.9
## 4 Alabama Barbour County 男性 288.9 335.9 389.1
## 5 Alabama  Dallas County 男性 293.4 330.1 370.6
## 6 Alabama  Greene County 男性 255.9 328.1 416.6</code></pre>
</div>
<div id="地图数据" class="section level3">
<h3>地图数据</h3>
<p>接下来，需要准备地图数据，<strong>maps</strong> 包内置了美国州级、郡级两个多边形边界地图数据，下面以郡级数据为例</p>
<pre class="r"><code>library(maps)
county_map &lt;- map(database = &quot;county&quot;, fill = TRUE, plot = FALSE)
str(county_map)</code></pre>
<pre><code>## List of 4
##  $ x    : num [1:91033] -86.5 -86.5 -86.5 -86.6 -86.6 ...
##  $ y    : num [1:91033] 32.3 32.4 32.4 32.4 32.4 ...
##  $ range: num [1:4] -124.7 -67 25.1 49.4
##  $ names: chr [1:3085] &quot;alabama,autauga&quot; &quot;alabama,baldwin&quot; &quot;alabama,barbour&quot; &quot;alabama,bibb&quot; ...
##  - attr(*, &quot;class&quot;)= chr &quot;map&quot;</code></pre>
<p>county_map 的数据类型是 <code>map</code>，是由 R 语言内置的基本数据类型 list <strong>列表</strong>构造出来的，它有 4 个元素，分别是 x 经度、 y 纬度、 range 矩形边界和 names 每一块地理单元的名称。每一对经纬度代表一个点，多个点按照一定顺序可以形成线或封闭的多边形，从数据集 county_map 来看，美国 <strong>3085</strong> 个郡的多边形边界用 <strong>91033</strong> 个点表示，坐标点的数量是刻画地理边界精度的。</p>
<p>用 <strong>ggplot2</strong> 包绘制地图，需要将原 <code>map</code> 数据类型转化为 data.frame 数据框类型，<strong>ggplot2</strong> 包有函数 <code>map_data()</code> 来做转化。</p>
<pre class="r"><code>library(ggplot2)
# 获取州、郡级地图数据
us_state_map &lt;- map_data(map = &quot;state&quot;)
us_county_map &lt;- map_data(map = &quot;county&quot;)</code></pre>
<p>查看转化后的数据集 us_county_map，发现有 <strong>87949</strong> 行 <strong>6</strong> 列，group 变量表示郡分组编号，order 变量表示经纬度坐标点编号，region 和 subregion 变量分别表示州、郡名称。</p>
<pre class="r"><code>str(us_county_map)</code></pre>
<pre><code>## &#39;data.frame&#39;:    87949 obs. of  6 variables:
##  $ long     : num  -86.5 -86.5 -86.5 -86.6 -86.6 ...
##  $ lat      : num  32.3 32.4 32.4 32.4 32.4 ...
##  $ group    : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ order    : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ region   : chr  &quot;alabama&quot; &quot;alabama&quot; &quot;alabama&quot; &quot;alabama&quot; ...
##  $ subregion: chr  &quot;autauga&quot; &quot;autauga&quot; &quot;autauga&quot; &quot;autauga&quot; ...</code></pre>
<pre class="r"><code>head(us_county_map)</code></pre>
<pre><code>##     long   lat group order  region subregion
## 1 -86.51 32.35     1     1 alabama   autauga
## 2 -86.53 32.35     1     2 alabama   autauga
## 3 -86.55 32.37     1     3 alabama   autauga
## 4 -86.56 32.38     1     4 alabama   autauga
## 5 -86.58 32.38     1     5 alabama   autauga
## 6 -86.59 32.38     1     6 alabama   autauga</code></pre>
<p>从地图数据集 us_county_map 取出阿拉巴马州的情况，按郡县统计一下各个字段的数量。篇幅所限，下面仅展示部分数据记录，一共有 <strong>67</strong> 个郡县，其中用 51 个坐标点表示了 autauga 奥陶加郡的边界。这从原来的 <strong>91033</strong> 个点，经 <strong>ggplot2</strong> 包转化后，变成了 <strong>87949</strong> 个点，去掉了 county_map 中坐标为 NA 的 <strong>3084</strong> 个点。</p>
<pre class="r"><code>aggregate(
  data = us_county_map,
  x = . ~ region + subregion,
  FUN = length,
  subset = region == &quot;alabama&quot;
)</code></pre>
<pre><code>##     region  subregion long lat group order
## 1  alabama    autauga   51  51    51    51
## 2  alabama    baldwin  116 116   116   116
## 3  alabama    barbour   51  51    51    51
## 4  alabama       bibb   40  40    40    40
## 5  alabama     blount   69  69    69    69
....</code></pre>
<p>再看一下数据转化后，group（郡）的数量，是 <strong>3085</strong> 个，没错！</p>
<pre class="r"><code>length(unique(us_county_map$group))</code></pre>
<pre><code>## [1] 3085</code></pre>
<pre class="r"><code>length(unique(us_county_map$order))</code></pre>
<pre><code>## [1] 87949</code></pre>
</div>
<div id="数据合并" class="section level3">
<h3>数据合并</h3>
<p>接下来，需要将观测数据以<strong>左关联</strong>的方式合并到地图数据上，通常来说，地图数据是完整的，或者说地理范围是覆盖观测数据的。注意到 us_cancer_rates 中郡名称 county 字段和 us_county_map 中郡名称 subregion 字段的联系，先对 us_cancer_rates 做一些小小的数据变换操作，转小写和去掉郡名称中的 「county」。</p>
<pre class="r"><code>us_cancer_rates &lt;- within(us_cancer_rates, {
  state &lt;- tolower(state)
  county &lt;- tolower(county)
  county &lt;- gsub(pattern = &quot;( county)&quot;, replacement = &quot;&quot;, x = county)
})</code></pre>
<p>下面开始合并观测数据和地图数据，指定需要合并的两个数据集，以及按照哪些列合并，注意数据集和字段的顺序，让 region 对应 state，subregion 对应 county。</p>
<pre class="r"><code>us_cancer_rates2 &lt;- merge(
  x = us_county_map,
  y = us_cancer_rates,
  by.x = c(&quot;region&quot;, &quot;subregion&quot;),
  by.y = c(&quot;state&quot;, &quot;county&quot;),
  all.x = TRUE,
  sort = FALSE
)</code></pre>
<p>然后恢复地图数据中各个坐标点的顺序。</p>
<pre class="r"><code># 排序
us_cancer_rates2 &lt;- us_cancer_rates2[order(us_cancer_rates2$order), ]</code></pre>
<p>再来看看合并和排序后的数据集。</p>
<pre class="r"><code>str(us_cancer_rates2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    169496 obs. of  10 variables:
##  $ region   : chr  &quot;alabama&quot; &quot;alabama&quot; &quot;alabama&quot; &quot;alabama&quot; ...
##  $ subregion: chr  &quot;autauga&quot; &quot;autauga&quot; &quot;autauga&quot; &quot;autauga&quot; ...
##  $ long     : num  -86.5 -86.5 -86.5 -86.5 -86.5 ...
##  $ lat      : num  32.3 32.3 32.4 32.4 32.4 ...
##  $ group    : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ order    : int  1 1 2 2 3 3 4 4 5 5 ...
##  $ sex      : chr  &quot;女性&quot; &quot;男性&quot; &quot;女性&quot; &quot;男性&quot; ...
##  $ LCL95    : num  150 243 150 243 150 ...
##  $ rate     : num  174 283 174 283 174 ...
##  $ UCL95    : num  200 330 200 330 200 ...</code></pre>
<pre class="r"><code>head(us_cancer_rates2)</code></pre>
<pre><code>##     region subregion   long   lat group order  sex LCL95  rate UCL95
## 65 alabama   autauga -86.51 32.35     1     1 女性 149.8 173.6 200.3
## 66 alabama   autauga -86.51 32.35     1     1 男性 242.6 283.1 329.8
## 47 alabama   autauga -86.53 32.35     1     2 女性 149.8 173.6 200.3
## 48 alabama   autauga -86.53 32.35     1     2 男性 242.6 283.1 329.8
## 55 alabama   autauga -86.55 32.37     1     3 女性 149.8 173.6 200.3
## 56 alabama   autauga -86.55 32.37     1     3 男性 242.6 283.1 329.8</code></pre>
<p>发现，原地图数据集 us_county_map 的行数增加近一倍，但又不是一倍。<span class="math inline">\(169496 / 2 = 84748\)</span> 距离原 us_county_map 数据集的行数 87949，差了整整 3201，这是为什么呢？观测数据集 us_cancer_rates2 并没有覆盖美国本土连续的 48 州的所有郡，其实一开始，就知道原观测数据集 USCancerRates 只有 3041 行记录，最多 3041 个郡有数据。但，不知道的是缺失的分布情况，哪些郡县有缺失，以及分男女的缺失情况。</p>
<pre class="r"><code># 检查原数据集 USCancerRates 是否有缺失
us_cancer_rates_na &lt;- subset(x = us_cancer_rates, subset = is.na(rate))</code></pre>
<pre class="r"><code>str(us_cancer_rates_na)</code></pre>
<pre><code>## &#39;data.frame&#39;:    73 obs. of  6 variables:
##  $ state : chr  &quot;alaska&quot; &quot;alaska&quot; &quot;colorado&quot; &quot;idaho&quot; ...
##  $ county: &#39;AsIs&#39; chr  &quot;northwest arctic borough&quot; &quot;dillingham census area&quot; &quot;lincoln&quot; &quot;teton&quot; ...
##  $ sex   : chr  &quot;男性&quot; &quot;男性&quot; &quot;男性&quot; &quot;男性&quot; ...
##  $ LCL95 : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ rate  : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ UCL95 : num  NA NA NA NA NA NA NA NA NA NA ...</code></pre>
<pre class="r"><code>head(us_cancer_rates_na)</code></pre>
<pre><code>##         state                   county  sex LCL95 rate UCL95
## 3032   alaska northwest arctic borough 男性    NA   NA    NA
## 3033   alaska   dillingham census area 男性    NA   NA    NA
## 3034 colorado                  lincoln 男性    NA   NA    NA
## 3035    idaho                    teton 男性    NA   NA    NA
## 3036   kansas                    logan 男性    NA   NA    NA
## 3037 nebraska                 frontier 男性    NA   NA    NA</code></pre>
<pre class="r"><code># 分性别统计缺失数据的分布
table(us_cancer_rates_na$sex)</code></pre>
<pre><code>## 
## 女性 男性 
##   63   10</code></pre>
<p>由此可知，63 个郡的女性癌症死亡率数据缺失，而其男性癌症死亡率数据未缺失；有 10 个郡的男性癌症死亡率数据缺失，而其女性癌症死亡率数据未缺失；如果一个郡的男、女性癌症死亡率数据<strong>都</strong>缺失，那就不会记录到原数据集 USCancerRates 里。因 USCancerRates 缺失了一部分郡的数据，没关联上 us_county_map 的不会加倍。</p>
<p>最后，将癌症死亡率以等间距的方式简单分级。</p>
<pre class="r"><code>us_cancer_rates2$rate_d &lt;- cut(us_cancer_rates2$rate, breaks = 50 * 0:13)</code></pre>
<p>再去掉缺失完全没有死亡率数据的记录，不然分面绘图要出现 NA 的一面。</p>
<pre class="r"><code>us_cancer_rates2 &lt;- subset(x = us_cancer_rates2, subset = !is.na(sex))</code></pre>
</div>
</div>
<div id="数据展示" class="section level2">
<h2>数据展示</h2>
<p>终于来到画图的阶段了，<strong>ggplot2</strong> 包 + <strong>maps</strong> 包 + <strong>mapproj</strong> 包<span class="citation">(<a href="#ref-mapproj" role="doc-biblioref">McIlroy et al. 2022</a>)</span>的组合，意即在 <strong>maps</strong> 包和 <strong>mapproj</strong> 包的支撑下，<strong>ggplot2</strong> 包封装了两个函数，分别是地理几何图层 <code>geom_map()</code> 和坐标投影图层 <code>coord_map()</code>。主要绘图步骤如下：</p>
<ol style="list-style-type: decimal">
<li><p>以郡级地图数据 us_county_map 为基础，绘制地图底图，各郡填充灰色。</p></li>
<li><p>将观测数据 us_cancer_rates2 映射到地图上，收集到癌症死亡率数据的郡填充上颜色，覆盖掉默认的灰色，边界线也去掉。</p></li>
<li><p>以州级地图数据 us_state_map 为基础，绘制各州边界线，线条调细一些。</p></li>
<li><p>将坐标投影方式设置为方位角投影，视角中心设置在美国，视角中心可参考 <code>county_map$range</code> 设定的范围。</p></li>
<li><p>调色板设置为 plasma，缺失值填充为灰色，和背景底图一样。</p></li>
<li><p>添加主、副标题和图例标题，设置主题，字体样式和大小，主、副标题位置等细节。</p></li>
</ol>
<pre class="r"><code>ggplot(data = us_cancer_rates2, aes(long, lat, group = subregion)) +
  geom_map(aes(map_id = region),
    map = us_county_map,
    fill = &quot;grey80&quot;
  ) +
  geom_polygon(aes(group = group, fill = rate_d), color = NA) +
  geom_map(aes(map_id = region),
    map = us_state_map,
    colour = &quot;gray80&quot;, fill = NA, size = 0.15
  ) +
  coord_map(&quot;orthographic&quot;, orientation = c(39, -98, 0)) +
  scale_fill_viridis_d(option = &quot;plasma&quot;, na.value = &quot;grey80&quot;) +
  facet_wrap(~sex, ncol = 1, strip.position = &quot;top&quot;) +
  labs(
    fill = &quot;死亡率&quot;, title = &quot;1999-2003 年美国各个郡的年平均癌症死亡率&quot;,
    caption = &quot;数据源：美国国家癌症研究所&quot;
  ) +
  theme_void(base_size = 13) +
  theme(
    title = element_text(family = &quot;Noto Serif CJK SC&quot;),
    plot.title = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0)
  )</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ggplot2-maps"></span>
<img src="{{< blogdown/postref >}}index_files/figure-html/ggplot2-maps-1.png" alt="1999-2003 年美国各个郡的年平均癌症死亡率分布" width="768" />
<p class="caption">
图 2: 1999-2003 年美国各个郡的年平均癌症死亡率分布
</p>
</div>
<p>又有神奇的事情发生了，从图<a href="#fig:ggplot2-maps">2</a>不难看出，地图东南角缺了一块，路易斯安那州的地图数据都缺失了。而实际上，路易斯安那州是有收集到癌症死亡率数据的，且看：</p>
<pre class="r"><code># 篇幅所限仅展示部分数据
subset(x = us_cancer_rates, subset = state == &quot;louisiana&quot;)</code></pre>
<pre><code>##          state                      county  sex LCL95  rate UCL95
## 1075 louisiana             richland parish 男性 315.6 368.6 428.4
## 1076 louisiana              madison parish 男性 289.0 360.9 445.9
## 1077 louisiana              de soto parish 男性 302.0 349.3 402.4
## 1078 louisiana          st. bernard parish 男性 307.7 338.4 371.9
## 1079 louisiana           washington parish 男性 303.2 338.2 376.5
....</code></pre>
<p>可见，问题出在地图数据和观测数据的关联环节，再看路易斯安那州的地图数据：</p>
<pre class="r"><code># 篇幅所限仅展示部分数据
subset(x = us_county_map, subset = region == &quot;louisiana&quot;)</code></pre>
<pre><code>##         long   lat group order    region           subregion
## 32147 -92.62 30.48  1079 32147 louisiana              acadia
## 32148 -92.49 30.49  1079 32148 louisiana              acadia
## 32149 -92.24 30.49  1079 32149 louisiana              acadia
## 32150 -92.24 30.45  1079 32150 louisiana              acadia
## 32151 -92.18 30.45  1079 32151 louisiana              acadia
....</code></pre>
<p>仔细对比一下 county 字段，发现观测数据集里郡名称都带着 parish（教区），而 <strong>ggplot2</strong> 地图数据中没有。</p>
<pre class="r"><code># 篇幅所限仅展示部分数据
subset(x = us_county_map, subset = region == &quot;louisiana&quot;) |&gt;
  aggregate(. ~ region + subregion, length)</code></pre>
<pre><code>##       region           subregion long lat group order
## 1  louisiana              acadia   44  44    44    44
## 2  louisiana               allen   22  22    22    22
## 3  louisiana           ascension   39  39    39    39
## 4  louisiana          assumption   39  39    39    39
## 5  louisiana           avoyelles   66  66    66    66
....</code></pre>
<p>再看原 <strong>maps</strong> 包的地图数据集 county_map 中路易斯安那州的情况。</p>
<pre class="r"><code># 篇幅所限仅展示部分数据
grep(&quot;louisiana&quot;, x = county_map$names, value = T)</code></pre>
<pre><code>##  [1] &quot;louisiana,acadia&quot;              &quot;louisiana,allen&quot;              
##  [3] &quot;louisiana,ascension&quot;           &quot;louisiana,assumption&quot;         
##  [5] &quot;louisiana,avoyelles&quot;           &quot;louisiana,beauregard&quot;         
##  [7] &quot;louisiana,bienville&quot;           &quot;louisiana,bossier&quot;            
##  [9] &quot;louisiana,caddo&quot;               &quot;louisiana,calcasieu&quot;          
## [11] &quot;louisiana,caldwell&quot;            &quot;louisiana,cameron&quot;            
....</code></pre>
<p>原来，在观测数据集里，路易斯安那州下属各行政单元不叫某某郡县 County 而叫某某教区 Parish。因此，缓解办法是在观测数据的处理一节，county 字段中取值包含 parish 的做一些替换。</p>
<pre class="r"><code>us_cancer_rates &lt;- within(us_cancer_rates, {
  state &lt;- tolower(state)
  county &lt;- tolower(county)
  # 既要去掉 county 又要去掉 parish 还要去掉什么呢？
  county &lt;- gsub(pattern = &quot;( county)|( parish)&quot;, replacement = &quot;&quot;, x = county)
})</code></pre>
<p>为什么文章《地区分布图及其应用》没有出现图<a href="#fig:ggplot2-maps">2</a>的缺失情况？因为用的是原始数据集 USCancerRates 的行名做匹配，且看路易斯安那州的情况：</p>
<pre class="r"><code># 篇幅所限仅展示部分数据
subset(x = USCancerRates, subset = state == &quot;Louisiana&quot;, select = c(&quot;state&quot;, &quot;county&quot;))</code></pre>
<pre><code>##                                   state                      county
## louisiana,richland            Louisiana             Richland Parish
## louisiana,madison             Louisiana              Madison Parish
## louisiana,de soto             Louisiana              De Soto Parish
## louisiana,st bernard          Louisiana          St. Bernard Parish
## louisiana,washington          Louisiana           Washington Parish
## louisiana,avoyelles           Louisiana            Avoyelles Parish
## louisiana,st john the baptist Louisiana St. John the Baptist Parish
## louisiana,st martin           Louisiana           St. Martin Parish
## louisiana,jackson             Louisiana              Jackson Parish
....</code></pre>
<p>像这样的数据情况，除非你有很好的数据探查工具，否则，在初始的数据探查阶段很难发现，更不会一开始就进行<strong>行级别</strong>的<strong>细粒度</strong>探查，数据可视化可以帮助我们了解数据质量，好的数据探查工具可以帮助我们提效，比如 <span class="citation">X. Cheng, Cook, and Hofmann (<a href="#ref-Cheng2015" role="doc-biblioref">2015</a>)</span> 用带图形用户界面的工具 可视化探索数据缺失情况。</p>
</div>
<div id="经验总结" class="section level2">
<h2>经验总结</h2>
<ol style="list-style-type: decimal">
<li><p>行政区划的名称在不同的体系下各有一套，美国人口调查局官方发布一套，美国国家癌症研究所发布癌症死亡率数据带一套， R 包 <strong>maps</strong> 二次加工一套，<strong>ggplot2</strong> 包在 <strong>maps</strong> 包基础上三次加工，又是一套，这种层层加工将地理单元的唯一编码 <a href="https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html">GEO_ID</a> （Geographic Identifiers，地理单元标识，简称 GEO_ID）/ <a href="https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards">FIPS</a>（<strong>F</strong>ederal <strong>I</strong>nformation <strong>P</strong>rocessing <strong>S</strong>tandards，联邦信息处理标准，简称 FIPS） 丢掉了，导致数据上难以关联准确，<strong>数据一致性</strong>丢失了，最终导致数据处理、分析和应用变复杂甚至不可行了。</p></li>
<li><p>行政区划的名称、辖区范围为适应社会经济发展做调整，国内每年行政区域的名称都有一些更改，比如撤县划市，区县、村镇、、街道合并等等，越靠近基层的行政单元更改的量越大。此外，在历史上，很多西方国家，调查统计人口、土地等基本国情的数据在各教区、教会、教堂，很多洗礼、结婚、丧葬由当地的牧师主持，教权影响力甚至大于政权 <span class="citation">(<a href="#ref-Chen1987" role="doc-biblioref">陈善林 and 张浙 1987</a>)</span>。</p></li>
<li><p>在文章<a href="https://cosx.org/2022/05/choropleth-map/">《地区分布图及其应用》</a>中，地图数据的获取从 <strong>maps</strong> 包到 <strong>usmapdata</strong> 包<span class="citation">(<a href="#ref-usmapdata" role="doc-biblioref">Di Lorenzo 2022</a>)</span>，再到 2019 年美国人口调查局，已经出现一些小问题。不同数据源或方法绘制的地图，仔细观察角角落落会发现路易斯安那州有些问题。<strong>maps</strong> 包和 <strong>latticeExtra</strong> 包绘图共用一份地图数据，它们地图上每个郡的数据是一样，而较新的地图数据，郡名称和 2003 年时可能有所不同。因此，地图数据的年份最好和观测数据采纳的一致，观测数据中关于地理单元，最好使用 GEO_ID/FIPS 之类的国家统一编码。</p></li>
<li><p><a href="https://r-graphics.org/recipe-miscgraph-choropleth">《R Graphics Cookbook》</a><span class="citation">(<a href="#ref-Chang2018" role="doc-biblioref">Chang 2018</a>)</span>第二版仍然在介绍 <strong>ggplot2</strong> 包组合 <strong>maps</strong> 包制作地图的方法。<a href="https://ggplot2-book.org/maps.html">《ggplot2: Elegant Graphics for Data Analysis》</a><span class="citation">(<a href="#ref-Wickham2022" role="doc-biblioref">Wickham 2022</a>)</span>在最新的第三版中开始考虑到制作地图的准确性问题，并大篇幅介绍 <strong>sf</strong> 包。 <strong>lattice</strong> 包<span class="citation">(<a href="#ref-Sarkar2008" role="doc-biblioref">Sarkar 2008</a>)</span>及其生态扩展包 <strong>latticeExtra</strong> 稳定成熟，<a href="https://github.com/deepayan/lattice/issues/11">没啥要改的了</a>，内置的一些风格主题，效果也不错，比如经济学人杂志主题。</p>
<div class="full-width">
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:sunspot-year"></span>
<img src="{{< blogdown/postref >}}index_files/figure-html/sunspot-year-1.png" alt="太阳黑子数量变化趋势" width="1152" />
<p class="caption">
图 3: 太阳黑子数量变化趋势
</p>
</div>
</div></li>
<li><p>最后，关于图形配色，简单谈一点，根据需要选择，R 内置了丰富的调色板，应有尽有，详见帮助文档<code>?hcl.pals()</code>！</p>
<div class="full-width">
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:colorspace-hcl-palettes"></span>
<img src="{{< blogdown/postref >}}index_files/figure-html/colorspace-hcl-palettes-1.png" alt="R 内置的 HCL 系调色板" width="1440" />
<p class="caption">
图 4: R 内置的 HCL 系调色板
</p>
</div>
</div></li>
</ol>
</div>
</div>
<div id="数据操作杂谈" class="section level1">
<h1>数据操作杂谈</h1>
<blockquote>
<p>我还是从前那个少年<br />
没有一丝丝改变<br />
时间只不过是考验<br />
种在心中信念丝毫未减</p>
<p>— 梦然·《少年》</p>
</blockquote>
<p>Base R 是指 R 软件正常运行所必须的一组 R 包集合，共有 14 个 R 包，<a href="https://www.r-project.org/foundation/members.html">R 核心团队</a>负责长期维护和开发。</p>
<pre><code> [1] &quot;base&quot;      &quot;tools&quot;     &quot;utils&quot;     &quot;grDevices&quot; &quot;graphics&quot;  &quot;stats&quot;    
 [7] &quot;datasets&quot;  &quot;methods&quot;   &quot;grid&quot;      &quot;splines&quot;   &quot;stats4&quot;    &quot;tcltk&quot;    
[13] &quot;compiler&quot;  &quot;parallel&quot; </code></pre>
<div id="长宽格式要怎么转" class="section level2">
<h2>长宽格式要怎么转</h2>
<p>大部分的数据可视化和统计建模函数要求「长格式」的数据，所以，从「宽格式」到「长格式」是更常见的变形操作。以上对数据集 USCancerRates 从「宽格式」到「长格式」的变形操作是非常典型的，读者可对照帮助文档 <code>?reshape()</code> 和如下两种方式理解其他传参方式对结果的影响，以加深对变形操作的理解。</p>
<pre class="r"><code># 方式二
reshape(
  data = USCancerRates,
  varying = list(
    LCL95 = c(&quot;LCL95.male&quot;, &quot;LCL95.female&quot;),
    rate = c(&quot;rate.male&quot;, &quot;rate.female&quot;),
    UCL95 = c(&quot;UCL95.male&quot;, &quot;UCL95.female&quot;)
  ),
  times = c(&quot;男性&quot;, &quot;女性&quot;), # 可选，最好填
  v.names = c(&quot;LCL95&quot;, &quot;rate&quot;, &quot;UCL95&quot;), # 可选，最好填
  timevar = &quot;sex&quot;, # 可选，最好填
  idvar = c(&quot;state&quot;, &quot;county&quot;), # 必填
  new.row.names = 1:(2 * 3041), # 可选，最好填
  direction = &quot;long&quot;
)
# 方式三
reshape(
  data = USCancerRates,
  varying = list(
    LCL95 = c(&quot;LCL95.male&quot;, &quot;LCL95.female&quot;),
    rate = c(&quot;rate.male&quot;, &quot;rate.female&quot;),
    UCL95 = c(&quot;UCL95.male&quot;, &quot;UCL95.female&quot;)
  ),
  # times = c(&quot;男性&quot;, &quot;女性&quot;),
  # v.names = c(&quot;LCL95&quot;, &quot;rate&quot;, &quot;UCL95&quot;),
  timevar = &quot;sex&quot;,
  idvar = c(&quot;state&quot;, &quot;county&quot;),
  new.row.names = 1:(2 * 3041),
  direction = &quot;long&quot;
)</code></pre>
<p>R 软件内置的函数 <code>reshape()</code> 有很丰富的解释。所谓的「宽格式」和「长格式」数据来源于纵向数据分析领域 longitudinal data analysis — 对同一对象的同一特征在不同时间点重复测量分析（假定对象没有随时间发生变化），也可以是对多个特征在不同时间点重复测量，这些特征就是所谓的时间变量（随时间变化的变量）timevar（time-varying variables），具体地，测量一个人的头发长度，有的特征随时间不会变化，比如性别、种族等，称之为时间常量（time-constant variables）。函数 <code>reshape()</code> 的参数就采用纵向数据分析的术语。R 是一个用于统计计算和绘图的编程语言和环境，主要由统计学家开发和维护，很多重要的函数要回归到统计上去理解，才会豁然开朗。</p>
</div>
<div id="base-r-永远是-base-r" class="section level2">
<h2>Base R 永远是 Base R</h2>
<blockquote>
<p>你大妈已经不是你六年前那大妈了，你大爷永远是你大爷。</p>
<p>— 2006年春晚小品《说事儿》</p>
</blockquote>
<p>Base R 定义了基础的数据类型，最常见的要数 vector 向量、 data.frame 数据框和 matrix 矩阵，也同时提供了很多相应的数据操作函数，没有什么数据操作是一个 Base R 函数搞不定的，有，就用两个！</p>
<p>常用数据操作的基本动作无非还是那么几个：</p>
<ol style="list-style-type: decimal">
<li>筛选行子集 <code>subset()</code> / <code>[</code></li>
<li>选择列子集 <code>subset()</code> / <code>[</code></li>
<li>新增/改变列 <code>within()</code></li>
<li>按列分组排序 <code>order()</code></li>
<li>按列分组聚合 <code>aggregate()</code></li>
<li>数据形状重塑 <code>reshape()</code></li>
<li>数据关联合并 <code>merge()</code>/<code>rbind()</code></li>
</ol>
<p>其它常用的辅助数据操作函数有：</p>
<ol style="list-style-type: decimal">
<li>数据查重替换 <code>duplicated()</code> / <code>replace()</code></li>
<li>数据记录完整性 <code>complete.cases()</code></li>
<li>判空、缺失值 <code>is.na()</code> / <code>is.nan()</code> / <code>is.integer()</code> 等</li>
<li>向量化操作函数，如 <code>vapply()</code> / <code>tapply()</code>/ <code>lapply()</code> 等</li>
</ol>
<p>熟悉这些函数的方式就是找个真实数据集，做一番数据分析，几乎可以肯定会使用以上大部分函数，举例来说，本文以及之前发布的<a href="/2022/04/choropleth-map/">《地区分布图及其应用》</a>、<a href="/2022/05/choropleth-map-animation/">《R 语言制作地区分布图及其动画》</a>等。</p>
<p>统计之都论坛每隔几天就有数据操作相关的问题冒出来，比如：</p>
<ul>
<li><a href="https://d.cosx.org/d/420763">Base R 数据操作的一致性问题</a></li>
<li><a href="https://d.cosx.org/d/421107">我竟然可以将数据框的列名保持一样</a></li>
<li><a href="https://d.cosx.org/d/421035">函数 <code>transform()</code> 自动转化列名是 feature 还是 bug</a></li>
<li><a href="https://d.cosx.org/d/420697/15">如何对数据框中的每行数据进行累加</a></li>
<li><a href="https://d.cosx.org/d/422889">如何做分组回归提取斜率和截距</a></li>
<li><a href="https://d.cosx.org/d/423059">如何根据自定义函数排序</a></li>
<li><a href="https://d.cosx.org/d/423101">列表转化为数据框</a></li>
<li><a href="https://d.cosx.org/d/423134">潜水论坛很久，有种感觉大家不是很喜欢tidyverse那一套的，可以问问为什么吗？</a></li>
<li><a href="https://d.cosx.org/d/423141">把数据框的每行按照某列拆分不同的行，只能用循环吗？</a></li>
<li><a href="https://d.cosx.org/d/423198">怎样把一段 <strong>tidy</strong> 版本的代码改写成 <strong>data.table</strong> 版本的</a></li>
<li>……</li>
</ul>
</div>
<div id="此-filter-非彼-filter" class="section level2">
<h2>此 filter 非彼 filter</h2>
<p>Base R 函数 <code>filter()</code> 的功能是非常强大的，本意是对时间序列应用一个线性滤波器，以前在大学物理实验课上见过这玩意，它可以让输入波经过特定的变换得到加强或减弱，看到的波都是被加强的，滤波器实际上是一个选频装置，让特定频段的波过滤出来。接下来，抛开物理背景知识（笔者知之甚少，基本还给物理老师了），只要知道 filter 会对原始数据做一个变换即可，这不正是数据操作中常用的 transform 吗！</p>
<p>根据函数帮助文档 <code>?filter</code>，参数 <code>sides = 1</code> 意味着 <code>method = "convolution"</code>，参数 <code>filter = c(2/3, 1/6, 1/6)</code> 是权重向量，按由近及远的顺序。先看个简单示例：</p>
<p><span class="math inline">\(y_i = \frac{2}{3} x_{i} + \frac{1}{6} x_{i - 1} + \frac{1}{6} x_{i - 2}, \quad i \geq 3\)</span></p>
<pre class="r"><code>x = 1:10
filter(x, filter = c(2/3, 1/6, 1/6), sides = 1)</code></pre>
<pre><code>## Time Series:
## Start = 1 
## End = 10 
## Frequency = 1 
##  [1]  NA  NA 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5</code></pre>
<p>下面以分组计算移动平均为例介绍函数 <code>filter()</code> 的妙用，毕竟时间序列平滑还是很常用的。</p>
<pre class="r"><code># 按某列分组对另一列移动平均
library(data.table)
dat &lt;- data.table(x = 1:12, y = rep(c(&quot;a&quot;, &quot;b&quot;), each = 3))
dat[, moving_average1 := filter(x, filter = rep(1 / 3, 3), sides = 1), by = &quot;y&quot;]
# 或者使用 data.table 提供的函数 frollmean
dat[ , moving_average2 := frollmean(x, n = 3), by = &quot;y&quot;]
# 或者使用更一般的函数 frollapply
dat[ , moving_average3 := frollapply(x, n = 3, FUN = mean), by = &quot;y&quot;]
dat</code></pre>
<pre><code>##      x y moving_average1 moving_average2 moving_average3
##  1:  1 a              NA              NA              NA
##  2:  2 a              NA              NA              NA
##  3:  3 a               2               2               2
##  4:  4 b              NA              NA              NA
##  5:  5 b              NA              NA              NA
##  6:  6 b               5               5               5
##  7:  7 a               4               4               4
##  8:  8 a               6               6               6
##  9:  9 a               8               8               8
## 10: 10 b               7               7               7
## 11: 11 b               9               9               9
## 12: 12 b              11              11              11</code></pre>
</div>
<div id="经验总结-1" class="section level2">
<h2>经验总结</h2>
<p>tidyverse <a href="https://d.cosx.org/d/421573-hugodown/4">大主教</a>在 Mango Solutions 组织的一场活动中给了主题为<a href="https://www.youtube.com/watch?v=vYwXMnC03I4">《Tidyverse: The <strong>greatest</strong> mistakes》</a>的报告，笔者认为本应是 「biggest」被换成了「greatest」，一字之差，天壤之别，还旁征博引，甚是有理！</p>
<blockquote>
<p>The cost of never making a mistake is very often never making a change at all. It’s just too incredibly hard to be sure. <a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a><br />
永不犯错的代价是一成不变。</p>
<p>— GeePaW Hill</p>
</blockquote>
<p>过度<a href="https://yihui.org/cn/2019/07/tidy-noise/">喧嚣</a>引来不少反抗，比如 <a href="https://heather.cs.ucdavis.edu/matloff.html">Norm Matloff</a> 的 <a href="https://github.com/matloff/TidyverseSkeptic">An opinionated view of the Tidyverse “dialect” of the R language</a>，Reece Goding 的 <a href="https://github.com/ReeceGoding/Frustration-One-Year-With-R">Frustration: One Year With R</a>，<a href="https://dirk.eddelbuettel.com/">Dirk Eddelbuettel</a> 等联合写的 <a href="https://www.tinyverse.org/">Lightweight is the right weight</a> 等等，都是实名实据地反抗。我只谈一点，tidyverse 之风已经吹入 R 语言社区的角角落落，即使读者像我一样在代码里不显式地使用它，却不得不考虑它的影响，有时要写一些额外的代码来应付。</p>
<div class="figure"><span style="display:block;" id="fig:rebuttal"></span>
<img src="img/rebuttal.jpg" style="width:75.0%" alt="" />
<p class="caption">图 5:  Base R vs data.table vs dplyr</p>
</div>
<p>关于数据操作，在不影响效率的情况下，笔者会优先选择 Base R 来做数据操作，若遇到小规模数据会考虑调用 <strong>data.table</strong> 来处理，若遇到大规模数据肯定是用 SQL 来处理，聚合完继续用 Base R 或 <strong>data.table</strong> 处理。工作几年下来，任凭窗外云卷云舒，在稳定和效率面前，我自岿然不动，看过不少<a href="https://yihui.org/cn/2019/07/tidy-noise/">净土代码</a>，也写过一些，所知有限，不敢示人，常晓其大意，<a href="https://d.cosx.org/d/423198/4">换之以 Base R</a>。</p>
<p>处理数百 GB 乃至 TB 级的海量数据，聚合计算通常都是由写 SQL 完成的，不太可能直接用 R 语言或 Python 语言去处理，什么牛逼的工具包都不行！SQL 聚合计算后得到的数据集就 KB 或 MB级，大约几千，几万或几十万，即使遇到几百万条记录，也是用 SQL 再按需聚合。只在最后，为了可视化和分析建模，对 SQL 查询后的数据做各种适应性变换，这变形重塑的数据操作是最常见的，也是最复杂的，并且在SQL中实现复杂而在R中非常简单。用户最大的痛点是非常难记住 reshape（变形） 的到底是谁，长变宽还是宽变长。R 语言社区陆续出现一些工具，从 <code>reshape()</code> 函数到 <strong>reshape</strong> 包<span class="citation">(<a href="#ref-Wickham2007" role="doc-biblioref">Wickham 2007</a>)</span>，再到 <strong>reshape2</strong> 包，再到 <strong>tidyr</strong> 包<span class="citation">(<a href="#ref-tidyr" role="doc-biblioref">Wickham and Girlich 2022</a>)</span>，一路折腾，还是应该回归到出发点来看待 <code>reshape()</code> 函数，其实不缺工具，就缺一些深入浅出、喜闻乐见、通俗易懂的文档介绍和广告宣传。</p>
</div>
</div>
<div id="也谈写作历程" class="section level1">
<h1>也谈写作历程</h1>
<p>《地区分布图及其应用》创作过程中经历了很多重要的节点：<a href="https://d.cosx.org/d/422907">起心动念</a>、选择方向、设定目标、收集数据、数据探查、数据分析、文章写作、完成初稿、<a href="https://d.cosx.org/d/423119">收集反馈</a>、初次修改、<a href="https://github.com/cosname/cosx.org/pull/1027">正式投稿</a>、评审反馈、反复修改、最终发布、交流反馈等。从起心动念到本《番外篇》发出止，历时正好<strong>四</strong>个月。当然不是四个月都干这么一件事，只是想把这个事情的来龙去脉都讲清楚，对整个事情做一些回顾，争取总结一些经验教训。</p>
<div id="预期目标" class="section level2">
<h2>预期目标</h2>
<p>就这篇《地区分布图及其应用》来说，大方向的选择没有太多犹疑。研究生阶段学习<a href="https://en.wikipedia.org/wiki/Geostatistics">「地统计学」</a>（Geostatistics），以空间广义线性混合效应模型在空间点数据（Point-referenced data or Geostatistics data）的分析和建模为主，属于空间数据分析的内容<span class="citation">(<a href="#ref-Banerjee2016" role="doc-biblioref">Banerjee 2016</a>)</span>。遗憾的是为了自己的学业无暇他顾，更别说空间统计是如何在现实世界应用的。前沿的论文搜集了很多，也根据学业需要读了不少，虽做了粗糙的分类，但是缺乏精细的组织和整理，最后，没能将一篇综述写出来，有点可惜。去年末开始捡时空统计的内容，重新捡起来和新学知识花费的时间是差不多的，三年过去，重读空间统计，有不一样的体会。有更多的目的性，要完成一篇文章，要熟悉几个方面的东西，比如空间区域数据（Areal data）及其可视化和分析等，同时也为了兴趣，也为了职业规划，也为了给软件工具栏目投稿。</p>
</div>
<div id="内容设想" class="section level2">
<h2>内容设想</h2>
<p>文章《地区分布图及其应用》最初的设想：</p>
<ol style="list-style-type: decimal">
<li><p>对我个人有足够的挑战，从头到尾地做一个稍大一点的数据项目，从找数据开始，看看自己是如何搞砸的，又是如何把它扶起来的，要经历怎样的痛苦挣扎。回过头来看，若对数据项目不感兴趣，极有可能半途而废。</p></li>
<li><p>为了在实际工作中更有借鉴意义，特意找了两个真实数据集：美国癌症研究所发布的 1999-2003 年度各郡年平均癌症死亡率数据，美国人口调查局发布的 2015-2019 年度家庭年收入数据。第一个准备用来介绍数据可视化及相关实现问题；第二个准备用来介绍数据分析和数据解读过程。</p></li>
<li><p>原计划一周完成写作，一周完成修改，实际做的过程中，发现屡屡超出预期，项目时间越拖越长。主观因素是刨根问底、学生心态、项目管理和经验不足。下面列举一些具体事项：</p>
<ol style="list-style-type: decimal">
<li><p>癌症死亡率数据虽已存在于 <strong>latticeExtra</strong> 包，但数据质量、数据指标及其计算过程都未能介绍清楚，它的作用仅是用于展示制作地区分布图（Choropleth map）的函数 <code>mapplot()</code>。按照笔者一贯的写作风格，肯定要刨根问底的，特别是它包含的年龄调整的年平均癌症死亡率究竟是个什么死亡率？怎么年龄调整的？为什么这么调整？因此，在<a href="https://statecancerprofiles.cancer.gov/">美国国家癌症研究所</a>（National Cancer Institute，简称 NCI）网站上花了不少时间去搞计算过程和逻辑。笔者在网站上没有找到癌症死亡率的区间估计过程，心有不甘，就去<a href="https://www.cdc.gov/">美国疾控预防中心</a>（Centers for Disease Control and Prevention，简称 CDC）找线索，理由是癌症死亡率和新冠死亡率在分地域、性别、年龄调整等维度上，指标统计口径应该类似，果不其然，详见 CDC 发布的报告 <span class="citation">Jiaquan et al. (<a href="#ref-Xu2021" role="doc-biblioref">2021</a>)</span>，其技术细节相当复杂，笔者只是略懂就不再细说了。</p></li>
<li><p>癌症死亡率数据在美国本土、阿拉斯加、夏威夷都有不少缺失，男、女死亡率数据各自有部分缺失，<strong>maps</strong> 包内置的美国郡级地图数据缺失阿拉斯加和夏威夷。为了完整的美国州、郡级地图数据，以及展示已有的全部癌症死亡率数据，就需要去找地图数据，这其实已经在和数据质量战斗了。本文前半部分重笔介绍 <strong>ggplot2</strong> 和 <strong>maps</strong> 包绘制地区分布图的过程，读者看完，想必已然明了。可以说，最初想的蛮好，实际上，并不简单，坑了自己一把。</p></li>
<li><p>用 <strong>latticeExtra</strong> 包制作地区分布图，为了加上州级边界线等细节，像只八爪章鱼在网上各种找材料，虽不想啃 Deepayan Sarkar 的书《Lattice: Multivariate Data Visualization with R》<span class="citation">(<a href="#ref-Sarkar2008" role="doc-biblioref">Sarkar 2008</a>)</span>，但要从整体上了解 Lattice 的轮廓，还是只有靠这本书。</p></li>
<li><p>为了代码稳定性、文章可重复性，有自信和能力避免任何和 <strong>dplyr</strong> 相关的代码，但项目时间上又有所延长。此外，文章合并入主站仓库没几天，<strong>ggplot2</strong> 的衍生包 <strong>biscale</strong> 包发布<a href="https://chris-prener.github.io/biscale/">重大版本 1.0.0</a>，二元地区分布图的代码<a href="https://github.com/cosname/cosx.org/commit/e4346a56eb36c861b449dbb233796c078f81df7b">不得不升级一下</a>。</p></li>
<li><p>地图数据获取上，有现成的 R 包 <strong>tidycensus</strong>，本来是很简单的事， 因<a href="https://d.cosx.org/d/422985">神奇的网络问题</a>，走了不少弯路，不过，最终装了 Docker，拉了基于 Ubuntu 的<a href="https://github.com/rocker-org/rocker-versioned2">容器镜像</a>，还是<a href="https://github.com/cosname/cosx.org/pull/1027/commits/efb3673ebb3ed3215f0ded636efeadebb41952cf">把路趟直了</a>。</p></li>
<li><p>《地区分布图及其应用》的初稿在数据解读方面做得很不好，更可笑的是家庭收入是月收入还是年收入都没搞清楚，足见数据背景知识的匮乏。好在数据整理的过程都有代码，重读指标含义，搜罗网上的材料，一对比就清楚了，顺带挖了一下美国人口调查局发布的指标体系的存储结构，后来，又看了世界银行的<a href="https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation">数据 API</a>和美国人口调查局发布的<a href="https://www.census.gov/data/developers/data-sets/international-database.html">其它数据 API</a>，指标体系都是按照某种形式的「长格式」存储。</p></li>
</ol></li>
</ol>
</div>
<div id="读者反馈" class="section level2">
<h2>读者反馈</h2>
<p>在探查年龄调整的癌症死亡率指标的计算过程时，发现美国人口的年龄结构数据，美国老年人口比例从 1940 年的 10% 左右增加到 2000 年的 15% 左右，60 年时间才增加 5% 左右，惊呆了！因此，写下了这一段内容，不过有些发散了，最终作罢。</p>
<blockquote>
<p>纵观过去，美国是没有老龄化现象的，惊不惊讶，意不意外！笔者初看有点意外，想了会儿又觉得是情理之中。有些基本问题无论从前还是未来，无论发达国家还是发展中国家，都要给出自己的解法。笔者不准备讨论与国家政策相关的敏感话题，仅推荐一本正儿八经的人物传记—现代统计学家《Neyman》<span class="citation">(<a href="#ref-Reid1982" role="doc-biblioref">Reid 1982</a>)</span>，有相应中译版《耐曼》<span class="citation">(<a href="#ref-Yao1985" role="doc-biblioref">Reid 1985</a>)</span>，里面给出了一些线索。</p>
</blockquote>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:us-pop-structure"></span>
<img src="{{< blogdown/postref >}}index_files/figure-html/us-pop-structure-1.png" alt="1940-2000年美国人口的年龄结构变化" width="576" />
<p class="caption">
图 6: 1940-2000年美国人口的年龄结构变化
</p>
</div>
<blockquote>
<p>笔者英文水平有限，看的是中文版，推荐有条件的读者尝试看英文版，应该会舒服得多。《Neyman》书中多次提及另一本卡尔·皮尔逊（Karl Person）的著作《The Grammar of Science》<span class="citation">(<a href="#ref-Person1911" role="doc-biblioref">Person 1911</a>)</span>，也有中译本《科学的规范》<span class="citation">(<a href="#ref-Person1998" role="doc-biblioref">Person 1998</a>)</span>，值得一读。众所周知，耐曼在波兰和英国时期和爱根·皮尔逊（E. S. Person）在假设检验和置信区间理论方面有大量合作，一起奠定了统计学严格的数学基础。耐曼的早期工作从卡尔·皮尔逊时代开始，研究了大量实际问题，所以，了解一些生活中实在的具体问题，就不会被 N-P 引理折磨了。于我个人而言，毕业以后，第一阶段应用，从书中来到工作中去，第二阶段理论，从工作中来到书中去。我的第一阶段正在进行中，第二阶段不知道什么时候开始。</p>
</blockquote>
<p>原文中另一个重要但没有谈的内容是坐标投影，正确的绘图姿势里是必须要交代的，原文在北卡州社区级家庭年收入分析中以提示形式插入了如下一段，后又删除，笔者考虑是过于强调细节。</p>
<blockquote>
<p><strong>sf</strong> 包内置的北卡州郡级地图数据集 <code>nc.gpkg</code> 坐标参考系为 <a href="https://epsg.io/4267"><code>EPSG:4267</code></a>，而通常使用的 <strong>leaflet</strong> 包<span class="citation">(<a href="#ref-leaflet" role="doc-biblioref">J. Cheng, Karambelkar, and Xie 2022</a>)</span>和 <strong>mapdeck</strong> 包<span class="citation">(<a href="#ref-mapdeck" role="doc-biblioref">Cooley 2020</a>)</span>需要地图数据集转化到 <a href="https://epsg.io/4326"><code>EPSG:4326</code></a>，其细微差别详见 Hiroaki Yutani 的博客 <span class="citation">(<a href="#ref-Yutani2018" role="doc-biblioref">Yutani 2018</a>)</span>。若使用国内的 Web 地图服务，一般需要地图数据转化到<a href="https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China">火星坐标系</a>，其间会存在一定的<a href="https://gis.stackexchange.com/questions/234202">漂移</a>。</p>
</blockquote>
<p>原文在 R 包依赖引入上比较谨慎，稳定高效地把活干了比什么都好，也趁此机会吐槽了一把 tidyverse ，见下文。应坛友的建议，此举可能伤害文章的内容，引起不必要的争论，因此，最终作罢。尽管 <strong>dplyr</strong> 及其 <strong>tidyverse</strong> 家族可能通过直接或间接的方式影响文章的可重复性，笔者也忍了，躲在一边静静地看 <strong>tidyverse</strong> 的粉丝们与他（她）们的教主一起共振。</p>
<blockquote>
<p>在写作过程中查找了不少材料，发现一个事实，即使在空间统计领域，崇拜 <strong>tidyverse</strong> <span class="citation">(<a href="#ref-Wickham2019" role="doc-biblioref">Wickham et al. 2019</a>)</span>的人也对 Base R 充满敌视，措辞非常严厉。笔者曾请教 <strong>tidycensus</strong> 包作者<a href="https://github.com/walkerke/tidycensus/issues/439">一些问题</a>，尽管问题本身和 Base R 没有太多关系，但人家会毫无理由地严厉地批评 <code>base::merge()</code> 而后推荐 <code>dplyr::left_join()</code>，读者遇到此类问题，请辩证地看待。据笔者深入了解，<strong>sf</strong> 及整个空间数据处理的基础框架都没有偏向 <strong>tidyverse</strong> 的意思，Edzer J. Pebesma 在 RStudio 2019 年会上的报告 — <a href="https://resources.rstudio.com/rstudio-conf-2019/spatial-data-science-in-the-tidyverse">Spatial data science in the Tidyverse</a> — 被很多人当作 <strong>sf</strong> 生态偏向 <strong>tidyverse</strong> 的标志。<strong>sf</strong> 是中立的，最初支持 Base R 数据操作和统计作图，后来支持部分净土操作，实际上 <strong>data.table</strong> <span class="citation">(<a href="#ref-Dowle2021" role="doc-biblioref">Dowle and Srinivasan 2021</a>)</span>也将在<a href="https://github.com/Rdatatable/data.table/pull/5224">下个版本</a>更好地支持 <strong>sf</strong> 的空间数据类型。此外，若将本文中的代码替换为<a href="https://yihui.org/cn/2019/07/tidy-noise/">净土代码</a>，将引入很多的 R 包依赖，并在不久的将来有丧失可重复性的风险。</p>
</blockquote>
<p>原文列出了一些未直接引用但有价值的材料，部分已经被笔者吸收，无法一一体现在文章中，毕竟需要取舍，否则，容易陷入汪洋大海，没了方向。感兴趣的读者看看这些拓展材料。</p>
<blockquote>
<p>在写作过程中，陆续遇到一些虽未直接引用但有价值的材料：</p>
<ul>
<li>芝加哥大学空间数据科学中心有一些培训材料，从入门开始讲解，比较系统全面细致，推荐读者看看<span class="citation">(<a href="#ref-Anselin2019" role="doc-biblioref">Anselin 2019</a>)</span>。</li>
<li>Edzer Pebesma 在历年 useR! 大会上的材料，如<a href="https://edzer.github.io/UseR2016/">2016年</a>、<a href="https://edzer.github.io/UseR2017/">2017年</a>、<a href="https://github.com/edzer/UseR2019">2019年</a>、<a href="https://edzer.github.io/UseR2020/">2020年</a>、<a href="https://edzer.github.io/UseR2021/">2021年</a>。</li>
<li>Edzer Pebesma 和 Roger Bivand 合著的书籍<a href="https://www.r-spatial.org/book">《Spatial Data Science with applications in R》</a> 架起了理论到应用的桥梁，详细阐述了空间数据科学的基本概念和统计方法，R 语言在空间统计生态的过去、现在和未来。</li>
</ul>
</blockquote>
<p>结合最近三年在平台型部门的工作，培养了一些商业分析思维，也学习了一些产品战略课程，还看了几本历史书，听了几场名人讲座，研读了几个商业案例，就<strong>膨胀</strong>了，在文章初版的「未来展望」中说了下面一段话，引来了不少<a href="https://d.cosx.org/d/423119/14">有意思的讨论</a>。</p>
<blockquote>
<p><strong>区域经济方面</strong>，改革开放40多年，最显著的变化就是城市化，大量人口进城，以互联网技术为基础，围绕吃穿住行、教育发展和休闲娱乐，餐饮外卖行业，新零售行业，房地产行业，出行行业，教育培训行业，以及休闲娱乐行业，互联网横向在各行各业渗透，纵向从一二线城市到三四五线城市下沉。大数据、互联网、人工智能等新技术极大地推动智慧城市规划和建设。「以经济建设为中心，一百年不动摇」必将在下一个四十年为城市发展持续注入动力。这就是当今中国社会最大的因。围绕此核心分析总体概况，从时间（趋势）、空间（地域）两个维度，拆解分析人群、行业变化，相信可以据此理解已经发生的、正在发生的和将要发生的一系列事情，而衡量中国城市化进程最直接的结果指标是中国城镇化率。</p>
</blockquote>
<p>笔者在癌症死亡率那个数据上，开头想当然地认为对数据集可以一查到底，像美国人口调查局发布的数据那样，只要愿意挖，想弄多清楚就可以弄多清楚，结果却是<strong>没有弄清楚</strong>！拿人家的二手数据做分析和处理，遇到种种数据问题。自己都不清楚的数据，分析起来就没有底气了，更不好给别人解释。有鉴于此，整个项目过程中，在数据获取、数据探查、数据展示、数据分析和数据解读等方面遇到的坑，告诉我如下的血泪教训。原文省略了很多背后的细节，写这些略显突兀，因而也删掉了，本文倒是以 <strong>ggplot2</strong> + <strong>maps</strong> 制作地区分布图为例略作了部分说明。</p>
<blockquote>
<p>最后，建议尽量寻求来源权威可靠的第一手材料，对手头现有的材料有追根溯源和交叉验证的热情。数据操作的过程应满足可重复性的基本要求，以便检查分析过程和结论。度量指标需要围绕专题分析的目标，并结合实际背景选择合适的维度拆解。借助统计工具分析隐藏数据中的深层规律，科学定量地刻画，并将规律用领域语言表达，最后，结合软件工具选用恰当的图形准确呈现，直观定性地表达降低沟通成本，快速形成决策建议，乃至落地推广。</p>
</blockquote>
</div>
<div id="评审反馈" class="section level2">
<h2>评审反馈</h2>
<p>感谢<a href="https://lijinzhang.com/">Lijing Zhang</a>抽空来审稿，提供许多建设性的<a href="https://github.com/cosname/cosx.org/pull/1027#pullrequestreview-964306791">修改意见</a>，丰富了北卡州家庭年收入的数据分析和解读，以及很多重要的写作细节。评审阶段完成 <strong>68</strong> 次提交，合并入统计之都主分支后还有 <strong>3</strong> 次提交，最后，文章质量得到极大的改善，其间<a href="https://yihui.org/">Yihui Xie</a>提供很多技术支持，特别是插入全宽图片和优化图片大小方面，在此一并表示感谢。</p>
</div>
</div>
<div id="环境信息" class="section level1">
<h1>环境信息</h1>
<p>本文是在 RStudio IDE 内用 R Markdown 编辑的，用 <strong>blogdown</strong> 构建网站，<a href="https://github.com/gohugoio/hugo">Hugo</a> 渲染 knitr 之后的 Markdown 文件，得益于 <strong>blogdown</strong> 对 R Markdown 格式的支持，图、表和参考文献的交叉引用非常方便，省了不少文字编辑功夫。文中使用了多个 R 包，为方便复现本文内容，下面列出详细的环境信息：</p>
<pre class="r"><code>xfun::session_info(packages = c(
  &quot;knitr&quot;, &quot;rmarkdown&quot;, &quot;blogdown&quot;,
  &quot;ggplot2&quot;, &quot;data.table&quot;, &quot;lattice&quot;, &quot;latticeExtra&quot;,
  &quot;maps&quot;, &quot;mapproj&quot;, &quot;ragg&quot;, &quot;colorspace&quot;
), dependencies = FALSE)</code></pre>
<pre><code>## R version 4.2.0 (2022-04-22)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Big Sur/Monterey 10.16
## 
## Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
## 
## Package version:
##   blogdown_1.10       colorspace_2.0-3    data.table_1.14.2  
##   ggplot2_3.3.6       knitr_1.39          lattice_0.20-45    
##   latticeExtra_0.6-29 mapproj_1.2.8       maps_3.4.0         
##   ragg_1.2.2          rmarkdown_2.14     
## 
## Pandoc version: 2.18
## 
## Hugo version: 0.98.0</code></pre>
</div>
<div id="参考文献" class="section level1 unnumbered">
<h1>参考文献</h1>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Anselin2019" class="csl-entry">
Anselin, Luc. 2019. <span>“Introduction to Spatial Data Science.”</span> <a href="https://spatialanalysis.github.io/tutorials/">https://spatialanalysis.github.io/tutorials/</a>.
</div>
<div id="ref-Banerjee2016" class="csl-entry">
Banerjee, Sudipto. 2016. <span>“Spatial Data Analysis.”</span> <em>Annual Review of Public Health</em> 37 (1): 47–60. <a href="https://doi.org/10.1146/annurev-publhealth-032315-021711">https://doi.org/10.1146/annurev-publhealth-032315-021711</a>.
</div>
<div id="ref-maps" class="csl-entry">
Becker, Richard A., Allan R. Wilks, Ray Brownrigg, Thomas P Minka, and Alex Deckmyn. 2021. <em><span class="nocase">maps</span>: Draw Geographical Maps</em>. <a href="https://CRAN.R-project.org/package=maps">https://CRAN.R-project.org/package=maps</a>.
</div>
<div id="ref-Chang2018" class="csl-entry">
Chang, Winston. 2018. <em>R Graphics Cookbook</em>. 2nd ed. O’Reilly Media. <a href="https://r-graphics.org/">https://r-graphics.org/</a>.
</div>
<div id="ref-leaflet" class="csl-entry">
Cheng, Joe, Bhaskar Karambelkar, and Yihui Xie. 2022. <em>Leaflet: Create Interactive Web Maps with the JavaScript Leaflet Library</em>. <a href="https://rstudio.github.io/leaflet/">https://rstudio.github.io/leaflet/</a>.
</div>
<div id="ref-Cheng2015" class="csl-entry">
Cheng, Xiaoyue, Dianne Cook, and Heike Hofmann. 2015. <span>“Visually Exploring Missing Values in Multivariable Data Using a Graphical User Interface.”</span> <em>Journal of Statistical Software</em> 68 (6): 1–23. <a href="https://doi.org/10.18637/jss.v068.i06">https://doi.org/10.18637/jss.v068.i06</a>.
</div>
<div id="ref-mapdeck" class="csl-entry">
Cooley, David. 2020. <em>Mapdeck: Interactive Maps Using ’Mapbox GL JS’ and ’Deck.gl’</em>. <a href="https://CRAN.R-project.org/package=mapdeck">https://CRAN.R-project.org/package=mapdeck</a>.
</div>
<div id="ref-usmapdata" class="csl-entry">
Di Lorenzo, Paolo. 2022. <em><span class="nocase">usmapdata</span>: Mapping Data for ’Usmap’ Package</em>. <a href="https://CRAN.R-project.org/package=usmapdata">https://CRAN.R-project.org/package=usmapdata</a>.
</div>
<div id="ref-Dowle2021" class="csl-entry">
Dowle, Matt, and Arun Srinivasan. 2021. <em><span class="nocase">data.table</span>: Extension of ‘Data.frame‘</em>. <a href="https://CRAN.R-project.org/package=data.table">https://CRAN.R-project.org/package=data.table</a>.
</div>
<div id="ref-mapsf" class="csl-entry">
Giraud, Timothée. 2022. <em><span class="nocase">mapsf</span>: Thematic Cartography</em>. <a href="https://CRAN.R-project.org/package=mapsf">https://CRAN.R-project.org/package=mapsf</a>.
</div>
<div id="ref-Xu2021" class="csl-entry">
Jiaquan, Xu, Sherry L. Murphy, Kenneth D. Kochanek, and Elizabeth Arias. 2021. <span>“Deaths: Final Data for 2019.”</span> 8. Vol. 70. National Vital Statistics Reports. National Center for Health Statistics. <a href="https://www.cdc.gov/nchs/data/nvsr/nvsr70/nvsr70-08-508.pdf">https://www.cdc.gov/nchs/data/nvsr/nvsr70/nvsr70-08-508.pdf</a>.
</div>
<div id="ref-mapproj" class="csl-entry">
McIlroy, Doug, Ray Brownrigg, Thomas P Minka, and Roger Bivand. 2022. <em><span class="nocase">mapproj</span>: Map Projections</em>. <a href="https://CRAN.R-project.org/package=mapproj">https://CRAN.R-project.org/package=mapproj</a>.
</div>
<div id="ref-Pebesma2018" class="csl-entry">
Pebesma, Edzer J. 2018. <span>“<span class="nocase">Simple Features for <span>R</span>: Standardized Support for Spatial Vector Data</span>.”</span> <em><span>The R Journal</span></em> 10 (1): 439–46. <a href="https://doi.org/10.32614/RJ-2018-009">https://doi.org/10.32614/RJ-2018-009</a>.
</div>
<div id="ref-Person1911" class="csl-entry">
Person, Karl. 1911. <em>The Grammar of Science</em>. 3rd ed. London: Adam; Charles Black.
</div>
<div id="ref-Person1998" class="csl-entry">
———. 1998. <em>科学的规范</em>. Translated by 李醒民. 北京: 华夏出版社.
</div>
<div id="ref-Reid1982" class="csl-entry">
Reid, Constance. 1982. <em>Neyman</em>. New York, NY: Springer-Verlag. <a href="https://doi.org/10.1007/978-1-4612-5754-7">https://doi.org/10.1007/978-1-4612-5754-7</a>.
</div>
<div id="ref-Yao1985" class="csl-entry">
———. 1985. <em>耐曼</em>. Translated by 姚慕生, 陈克艰, and 王顺义等. 上海: 上海翻译出版公司.
</div>
<div id="ref-Sarkar2008" class="csl-entry">
Sarkar, Deepayan. 2008. <em><span>Lattice</span>: Multivariate Data Visualization with <span>R</span></em>. New York: Springer-Verlag. <a href="http://lmdvr.r-forge.r-project.org">http://lmdvr.r-forge.r-project.org</a>.
</div>
<div id="ref-latticeExtra" class="csl-entry">
Sarkar, Deepayan, and Felix Andrews. 2019. <em><span class="nocase">latticeExtra</span>: Extra Graphical Utilities Based on Lattice</em>. <a href="https://CRAN.R-project.org/package=latticeExtra">https://CRAN.R-project.org/package=latticeExtra</a>.
</div>
<div id="ref-Tennekes2018" class="csl-entry">
Tennekes, Martijn. 2018. <span>“<span class="nocase">tmap</span>: Thematic Maps in <span>R</span>.”</span> <em>Journal of Statistical Software</em> 84 (6): 1–39. <a href="https://doi.org/10.18637/jss.v084.i06">https://doi.org/10.18637/jss.v084.i06</a>.
</div>
<div id="ref-Wickham2007" class="csl-entry">
Wickham, Hadley. 2007. <span>“Reshaping Data with the <span class="nocase">reshape</span> Package.”</span> <em>Journal of Statistical Software</em> 21 (12). <a href="https://www.jstatsoft.org/v21/i12/">https://www.jstatsoft.org/v21/i12/</a>.
</div>
<div id="ref-Wickham2022" class="csl-entry">
———. 2022. <em><span class="nocase">ggplot2</span>: Elegant Graphics for Data Analysis</em>. 3rd ed. Springer-Verlag New York. <a href="https://ggplot2-book.org/">https://ggplot2-book.org/</a>.
</div>
<div id="ref-Wickham2019" class="csl-entry">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-tidyr" class="csl-entry">
Wickham, Hadley, and Maximilian Girlich. 2022. <em><span class="nocase">tidyr</span>: Tidy Messy Data</em>. <a href="https://CRAN.R-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a>.
</div>
<div id="ref-Yutani2018" class="csl-entry">
Yutani, Hiroaki. 2018. <span>“Plot <span class="nocase">geom_sf()</span> on <span>OpenStreetMap</span> Tiles.”</span> <a href="https://yutani.rbind.io/post/2018-06-09-plot-osm-tiles/">https://yutani.rbind.io/post/2018-06-09-plot-osm-tiles/</a>.
</div>
<div id="ref-Chen1987" class="csl-entry">
陈善林, and 张浙. 1987. <em>统计发展史</em>. 北京: 立信会计图书用品社.
</div>
</div>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p><a href="https://www.geepawhill.org/2019/07/16/try-different-not-harder/" class="uri">https://www.geepawhill.org/2019/07/16/try-different-not-harder/</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
